stages:
  - BuildPackage
  - UnitTest
  - Profiling

RelWithDebInfo:
  stage: BuildPackage
  image: harbor.internal.moqi.ai/mochix/ubuntu22.04_base:0.0.3
  cache:
    key: ${CI_JOB_NAME}-cargo
    paths:
      - ./.cargo/registry/
    policy: pull-push
  before_script:
    - mkdir -p ./.cargo/registry/
    - du -h -d 1 ./.cargo/registry/
    - rsync -av --ignore-existing ./.cargo/registry/ /root/.cargo/registry/
  script:
    - git submodule update --init --recursive
    - mkdir -p build_packages
    - >
      cmake --no-warn-unused-cli
      -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
      -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
      -DCMAKE_C_COMPILER:FILEPATH=$(command -v clang-15)
      -DCMAKE_CXX_COMPILER:FILEPATH=$(command -v clang++-15)
      -S. -B./build_packages -G Ninja
    - cmake --build ./build_packages --config RelWithDebInfo --target all
    - mkdir -p packages
    - cp ./build_packages/benchmark/tantivy_search_benchmark ./packages
    - cp ./build_packages/libtantivy_search.a ./packages
    - cp ./build_packages/tests/throughput/throughput_test ./packages
    - cp ./build_packages/tests/unit_test/unit_tests ./packages
    - tar -czvf packages.tar.gz ./packages
    - md5sum ./packages/*
    - md5sum packages.tar.gz
    - ls -lh ./packages
    - ls -lh packages.tar.gz
    - du -h -d 1 /root/.cargo/registry/
    - rsync -av --ignore-existing /root/.cargo/registry/ ./.cargo/registry/ 
  artifacts:
    name: "packages"
    expire_in: 2 week
    paths:
      - packages.tar.gz


UnitTest:
  stage: UnitTest
  needs:
    - job: RelWithDebInfo
      artifacts: true
  image: harbor.internal.moqi.ai/mochix/ubuntu22.04_base:0.0.3
  script:
    - tar -zxvf packages.tar.gz
    - ./packages/unit_tests

GoogleBenchmark:
  stage: Profiling
  needs:
    - job: UnitTest
      artifacts: false
    - job: RelWithDebInfo
      artifacts: true
  image: harbor.internal.moqi.ai/mochix/ubuntu22.04_base:0.0.3
  script:
    - if [ ! -f scripts/query_terms.json ] || [ ! -f scripts/wiki_560w.json ]; then bash scripts/download_datasets.sh; fi
    # - tar -zxvf packages.tar.gz
    # - ./packages/tantivy_search_benchmark --qtp=scripts/query_terms.json --dp=scripts/wiki_560w.json --ip=./temp --sbi=false | tee google_benchmark_results.txt
    # - md5sum google_benchmark_results.txt
  cache:
    key: ${CI_JOB_NAME}-datasets
    paths:
      - scripts/query_terms.json
      - scripts/wiki_560w.json
    policy: pull-push
  # artifacts:
  #   name: "google_benchmark_results"
  #   expire_in: 2 week
  #   paths:
  #     - google_benchmark_results.txt

  