stages:
  - BuildPackage
  - UnitTest
  - Profiling

RelWithDebInfo:
  stage: BuildPackage
  image: harbor.internal.moqi.ai/mochix/ubuntu22.04_base:0.0.2
  script:
    - git submodule update --init --recursive
    - mkdir -p build_packages
    - >
      cmake --no-warn-unused-cli
      -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
      -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
      -DCMAKE_C_COMPILER:FILEPATH=$(command -v clang-15)
      -DCMAKE_CXX_COMPILER:FILEPATH=$(command -v clang++-15)
      -S. -B./build_packages -G Ninja
    - cmake --build ./build_packages --config RelWithDebInfo --target all
    - mkdir -p packages
    - cp ./build_packages/benchmark/tantivy_search_benchmark ./packages
    - cp ./build_packages/libtantivy_search.a ./packages
    - cp ./build_packages/tests/throughput/throughput_test ./packages
    - cp ./build_packages/tests/unit_test/unit_tests ./packages
    - tar -czvf packages.tar.gz ./packages
    - md5sum ./packages/*
    - md5sum packages.tar.gz
    - ls -lh ./packages
    - ls -lh packages.tar.gz
  artifacts:
    name: "packages"
    expire_in: 2 week
    paths:
      - packages.tar.gz


UnitTest:
  stage: UnitTest
  image: harbor.internal.moqi.ai/mochix/ubuntu22.04_base:0.0.2
  needs:
    - job: RelWithDebInfo
      artifacts: true
  artifacts:
    name: "packages"
    paths:
      - packages.tar.gz
    when: always
  scripts:
    - tar -zxvf packages.tar.gz
    - ./packages/unit_tests